const SMART_LIST_IDS = {
  ALL_TASKS: 'ALL_TASKS',
  DO_TODAY: "DO_TODAY",
  DO_TOMORROW: "DO_TOMORROW",
  DO_LATER: "DO_LATER",
  NEXT_WEEK: "NEXT_WEEK",
  ASSIGNED: "ASSIGNED",
  ASSIGNED_TO_ME: "ASSIGNED_TO_ME",
  WITH_REMINDERS: "WITH_REMINDERS",
  ROUTINES: "ROUTINES",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
  STARRED: "STARRED",
  PINNED: "PINNED",
  WITH_DUE_DATES: "WITH_DUE_DATES",
} as const;

export default SMART_LIST_IDS